#!/bin/bash
#Author Guilherme Fontenele

nc='\033[0m' # No Color
black='\033[0;30m'
red='\033[0;31m'
green='\033[0;32m'
orange='\033[0;33m'
blue='\033[0;34m'
purple='\033[0;35m'
cyan='\033[0;36m'
lightgray='\033[0;37m'
darkgray='\033[1;30m'
lightred='\033[1;31m'
lightgreen='\033[1;32m'
yellow='\033[1;33m'
lightblue='\033[1;34m'
lightpurple='\033[1;35m'
lightcyan='\033[1;36m'
white='\033[1;37m'

dir=`dirname $0`
cd $dir

has_nodejs=`which nodejs`

if [ "$EUID" -ne 0 ]
  then echo -e "${red}ERROR${nc} Please run as ${orange}root${nc}"
  exit
fi

if [[ -z "$has_nodejs" ]]; then
    echo -e "${red}ERROR${nc} Please install ${orange}nodejs${nc}: ${orange}sudo apt-get install nodejs${nc} or ${orange}sudo yum install nodejs${nc}"
    exit 1
fi

if [ ! -d "./node_modules" ]; then
    npm install
fi

if [ ! -f "/etc/systemd/system/docker-manager.service" ]; then
    echo "[Service]
ExecStart=/Applications/docker-manager/service
Restart=always
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=docker-manager
User=root
Group=root
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/docker-manager.service
fi

echo -e "${orange}DockerManager installed successfully!${nc} Thanks for using DockerManager!!!"
echo -e "Please run '${orange}service docker-manager start${nc}' to start docker-manager application then open the URL ${orange}http://localhost:31337${nc}"