#!/bin/bash
#Author Guilherme Fontenele

dir=`dirname $0`
cd $dir

has_nodejs=`which nodejs`

if [[ -z "$has_nodejs" ]]; then
    echo "ERROR: Please install nodejs: sudo apt-get install nodejs or sudo yum install nodejs"
    exit 1
fi

has_pm2=`which pm2`

if [[ -z "$has_pm2" ]]; then
    echo "ERROR: Please install pm2: sudo npm install -g pm2"
    exit 1
fi

if [ ! -d "./node_modules" ]; then
    npm install
fi

pm2 list

pm2 start -f web.js --name "docker-manager"
#echo "$PWD"
#echo `dirname $0`