#!/bin/bash
#Author Guilherme Fontenele

nc='\033[0m' # No Color
black='\033[0;30m'
red='\033[0;31m'
green='\033[0;32m'
orange='\033[0;33m'
blue='\033[0;34m'
purple='\033[0;35m'
cyan='\033[0;36m'
lightgray='\033[0;37m'
darkgray='\033[1;30m'
lightred='\033[1;31m'
lightgreen='\033[1;32m'
yellow='\033[1;33m'
lightblue='\033[1;34m'
lightpurple='\033[1;35m'
lightcyan='\033[1;36m'
white='\033[1;37m'


dir=`dirname $0`
cd $dir

has_nodejs=`which nodejs`

if [[ -z "$has_nodejs" ]]; then
    echo -e "${red}ERROR${nc} Please install ${orange}nodejs${nc}: ${orange}sudo apt-get install nodejs${nc} or ${orange}sudo yum install nodejs${nc}"
    exit 1
fi

if [ ! -d "./node_modules" ]; then
    echo -e "Installing dependences..."
    npm install
fi

echo -e "${orange}Starting DockerManager..."
$has_nodejs web.js
echo -e "${orange}DockerManager${nc} started successfully!"
