#!/bin/bash
#Author Guilherme Fontenele

nc='\033[0m' # No Color
black='\033[0;30m'
red='\033[0;31m'
green='\033[0;32m'
orange='\033[0;33m'
blue='\033[0;34m'
purple='\033[0;35m'
cyan='\033[0;36m'
lightgray='\033[0;37m'
darkgray='\033[1;30m'
lightred='\033[1;31m'
lightgreen='\033[1;32m'
yellow='\033[1;33m'
lightblue='\033[1;34m'
lightpurple='\033[1;35m'
lightcyan='\033[1;36m'
white='\033[1;37m'

if [ "$EUID" -ne 0 ]
  then echo -e "${red}ERROR${nc} Please run as ${orange}root${nc}"
  exit
fi

service docker-manager stop

if [ -f "/etc/systemd/system/docker-manager.service" ]; then
    rm /etc/systemd/system/docker-manager.service
fi

echo -e "${orange}DockerManager uninstalled successfully!${nc} Thanks for using DockerManager!!!"

cd /
rm -Rf /Applications/docker-manager/